# () - обязательный параметр; [] - необязательный параметр
# Чтобы сделать свои цифры, необходимо загрузить схематики 4 x 8 с помощью команды /sch
# Сначала нажимаете ПКМ палкой по верхнему левому блоку и пишите
# /sch set (цифра)
# Чтобы проверить схематику, нужно отойти на пустое пространство и написать
# /sch place (цифра)

# Чтобы заспавнить часы, необходимо прописать команду /spawnclock [часовой пояс]

# Разрешения:
# superclock.setschematic - разрешение на использование команды /sch
# superclock.spawnclock - разрешение на использование команды /superclock
# superclock.select - разрешение на выделение схематики

time-zone: 'UTC'
format: 'HH:mm:ss'