name: SuperClock
version: '${project.version}'
main: me.korolkotov.superclock.Main
api-version: '1.16'
authors: [KoroLKotov, Masti]
description: Plugin for tournament

permissions:
  superclock.setschematic:
    default: op

  superclock.spawnclock:
    default: op

  superclock.select:
    default: op

commands:
  spawnclock:
    usage: /spawnclock
  sch:
    usage: /sch [place|set]