name: SuperClock
version: '${project.version}'
main: me.korolkotov.superclock.Main
api-version: '1.16'
authors: [KoroLKotov, Masti]
description: Plugin for tournament

commands:
  spawnclock:
    usage: /spawnclock